server:
  port: 8081

spring:
  application:
    name: catalogue

  profiles:
    active:
      - database
      - rabbitmq
      - logging
      - swagger

  config:
    import: optional:configserver:http://didactic-config-server:8888

  cloud:
    config:
      label: main

  # ===== Datasource (H2) =====
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    properties:
      hibernate:
        ddl-auto: none
        format_sql: false
      show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#    listener:
#      simple:
#        default-requeue-rejected: false

logging:
  level:
    root: INFO
    org.springframework.amqp: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

springdoc:
  swagger-ui:
    url: /openapi/catalogue.yaml
    disable-swagger-default-url: true

# ===== Eureka (MUST BE AT ROOT LEVEL) =====
eureka:
  instance:
    hostname: catalogue
    prefer-ip-address: false

  client:
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
